version: "3.8"

services:
  # Main Next.js application
  app:
    build:
      context: ./miniapp/aurum-circle-miniapp
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - ./miniapp/aurum-circle-miniapp/public/models:/app/public/models
    restart: unless-stopped
    networks:
      - aurum-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - aurum-network

  # ML Face Scoring API
  ml-api:
    build:
      context: ./miniapp/aurum-circle-miniapp/ml-face-score-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - ./miniapp/aurum-circle-miniapp/ml-face-score-api/temp:/app/temp
      - ./miniapp/aurum-circle-miniapp/ml-face-score-api/models:/app/models
    restart: unless-stopped
    networks:
      - aurum-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - aurum-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  aurum-network:
    driver: bridge
    name: aurum-network-prod
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  qdrant_storage:
  redis_data:
