services:
  # Main Next.js application
  app:
    build:
      context: ./miniapp/aurum-circle-miniapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    volumes:
      - ./miniapp/aurum-circle-miniapp/public/models:/app/public/models
    restart: unless-stopped
    networks:
      - aurum-network

  # ML Face Scoring API
  ml-api:
    build:
      context: ./miniapp/aurum-circle-miniapp/ml-face-score-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - ./miniapp/aurum-circle-miniapp/ml-face-score-api/temp:/app/temp
      - ./miniapp/aurum-circle-miniapp/ml-face-score-api/models:/app/models
    restart: unless-stopped
    networks:
      - aurum-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d
    depends_on:
      - app
      - ml-api
    restart: unless-stopped
