services:
  face-detection-service:
    build:
      context: ./aurum-ml-services
      dockerfile: face-detection/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - RUST_LOG=info
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  face-embedding-service:
    build:
      context: ./aurum-ml-services
      dockerfile: face-embedding/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - RUST_LOG=info
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - face-detection-service
      - face-embedding-service
    restart: unless-stopped
