version: '3.8'

services:
  # Redis for job queue
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Main API service
  ml-api:
    build: .
    ports:
      - "80:3000"  # Expose on port 80 for public access
    depends_on:
      - redis
    volumes:
      - ./temp:/app/temp
      - ./models:/app/models
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Worker processes (scale as needed)
  ml-worker:
    build: .
    depends_on:
      - redis
    volumes:
      - ./temp:/app/temp
      - ./models:/app/models
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    command: node dist/worker.js
    restart: unless-stopped

volumes:
  redis_data: