services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./temp:/app/temp
      - ./models:/app/models
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm start
