version: "3.8"

services:
  face-detection:
    build:
      context: .
      dockerfile: face-detection/Dockerfile
      target: builder
    ports:
      - "8001:8001"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    volumes:
      - ./models:/app/models
    command: cargo run --bin face-detection

  face-embedding:
    build:
      context: .
      dockerfile: face-embedding/Dockerfile
      target: builder
    ports:
      - "8002:8002"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    volumes:
      - ./models:/app/models
    command: cargo run --bin face-embedding

  # Development database (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
