[monitoring]
check_interval_seconds = 300
max_concurrent_builds = 3
build_timeout_seconds = 1800
health_check_timeout_seconds = 30

[services]
services = [
    { name = "face-detection", path = "../face-detection", dockerfile = "Dockerfile" },
    { name = "face-embedding", path = "../face-embedding", dockerfile = "Dockerfile" },
    { name = "common", path = "../common", dockerfile = "Dockerfile" },
]

[git]
repository_path = "../"
main_branch = "main"
max_commits_to_check = 50
binary_search_depth = 10

[docker]
registry_url = "localhost:5000"
build_context_path = "."
dockerfile_path = "Dockerfile"
image_prefix = "aurum-ml"

[notifications]
slack_webhook_url = ""
discord_webhook_url = ""
email_smtp_server = ""
email_smtp_port = 587
email_username = ""
email_password = ""
email_from = "build-monitor@aurum.com"
email_to = ["admin@aurum.com"]

[web]
host = "0.0.0.0"
port = 8080
enable_dashboard = true

[environments]
dev = { docker_tag = "dev", build_args = { "RUST_VERSION" = "1.82" } }
staging = { docker_tag = "staging", build_args = { "RUST_VERSION" = "1.82" } }
prod = { docker_tag = "latest", build_args = { "RUST_VERSION" = "1.82" } }

[logging]
level = "info"
log_file = "build-monitor.log"
max_log_size_mb = 100
max_log_files = 5